language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  
install:
  - pip install -r requirements.txt

script:
  - cd tests && pytest

notifications:
  email:
    recipients:
      - dev.moreal@gmail.com
    on_success: change # default: change
    on_failure: change # default: always